export class Roles {
  static ROLE_CADASTRO_USUARIO: string = "ROLE_CADASTRO_USUARIO";
  static ROLE_CADASTRO_PERFIL: string = "ROLE_CADASTRO_PERFIL";
  static ROLE_LISTAGEM_USUARIO: string = "ROLE_LISTAGEM_USUARIO";
  static ROLE_ACESSO_SISTEMA: string = "ROLE_ACESSO_SISTEMA";
  static ROLE_CONCEDER_PERMISSAO: string = "ROLE_CONCEDER_PERMISSAO";
}
